name: usoundradio
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0
  audio_session: ^0.1.6+1
  just_audio: ^0.9.20
  cupertino_icons: ^1.0.2
  json_serializable: ^6.1.6
  json_annotation: ^4.4.0
  flutter_bloc: ^8.0.1
  http: ^0.13.3
  google_fonts: 2.2.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
